create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'paciente' check (role in ('admin', 'paciente')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  name text not null,
  cep text not null,
  street text,
  neighborhood text,
  city text,
  state text,
  address_label text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists specialties_name_unique
on public.specialties (lower(name));

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units (id) on delete cascade,
  specialty_id bigint not null references public.specialties (id) on delete cascade,
  starts_at timestamptz not null,
  is_available boolean not null default true,
  status text not null default 'disponivel' check (status in ('disponivel', 'reservado', 'indisponivel')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (unit_id, specialty_id, starts_at)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references public.profiles (id) on delete cascade,
  schedule_id bigint not null references public.schedules (id) on delete cascade,
  status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'cancelado')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists appointments_active_schedule_unique
on public.appointments (schedule_id)
where status in ('pendente', 'confirmado');

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_appointments_updated_at on public.appointments;
create trigger set_appointments_updated_at
before update on public.appointments
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'paciente')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.sync_schedule_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_exists boolean;
  target_schedule_id bigint;
begin
  target_schedule_id := coalesce(new.schedule_id, old.schedule_id);

  select exists (
    select 1
    from public.appointments
    where schedule_id = target_schedule_id
      and status in ('pendente', 'confirmado')
  )
  into active_exists;

  update public.schedules
  set
    is_available = not active_exists,
    status = case when active_exists then 'reservado' else 'disponivel' end
  where id = target_schedule_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists sync_schedule_status_after_insert on public.appointments;
create trigger sync_schedule_status_after_insert
after insert on public.appointments
for each row
execute function public.sync_schedule_status();

drop trigger if exists sync_schedule_status_after_update on public.appointments;
create trigger sync_schedule_status_after_update
after update on public.appointments
for each row
execute function public.sync_schedule_status();

drop trigger if exists sync_schedule_status_after_delete on public.appointments;
create trigger sync_schedule_status_after_delete
after delete on public.appointments
for each row
execute function public.sync_schedule_status();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.units enable row level security;
alter table public.specialties enable row level security;
alter table public.schedules enable row level security;
alter table public.appointments enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin
on public.profiles
for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists profiles_insert_self_or_admin on public.profiles;
create policy profiles_insert_self_or_admin
on public.profiles
for insert
to authenticated
with check (auth.uid() = id or public.is_admin());

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists units_read_authenticated on public.units;
create policy units_read_authenticated
on public.units
for select
to authenticated
using (true);

drop policy if exists units_admin_write on public.units;
create policy units_admin_write
on public.units
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists specialties_read_authenticated on public.specialties;
create policy specialties_read_authenticated
on public.specialties
for select
to authenticated
using (true);

drop policy if exists specialties_admin_write on public.specialties;
create policy specialties_admin_write
on public.specialties
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists schedules_read_authenticated on public.schedules;
create policy schedules_read_authenticated
on public.schedules
for select
to authenticated
using (true);

drop policy if exists schedules_admin_write on public.schedules;
create policy schedules_admin_write
on public.schedules
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists appointments_read_owner_or_admin on public.appointments;
create policy appointments_read_owner_or_admin
on public.appointments
for select
to authenticated
using (auth.uid() = patient_id or public.is_admin());

drop policy if exists appointments_insert_owner_or_admin on public.appointments;
create policy appointments_insert_owner_or_admin
on public.appointments
for insert
to authenticated
with check (auth.uid() = patient_id or public.is_admin());

drop policy if exists appointments_update_owner_or_admin on public.appointments;
create policy appointments_update_owner_or_admin
on public.appointments
for update
to authenticated
using (auth.uid() = patient_id or public.is_admin())
with check (auth.uid() = patient_id or public.is_admin());
