create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  name text not null,
  cep text not null,
  street text,
  neighborhood text,
  city text,
  state text,
  address_label text,
  image_url text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.units
add column if not exists image_url text;

create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists specialties_name_unique
on public.specialties (lower(name));

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units (id) on delete cascade,
  specialty_id bigint not null references public.specialties (id) on delete restrict,
  full_name text not null,
  crm text not null,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  cpf text unique,
  phone text,
  full_name text,
  role text not null default 'paciente' check (role in ('admin', 'gestor', 'paciente')),
  unit_id bigint references public.units (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units (id) on delete cascade,
  specialty_id bigint not null references public.specialties (id) on delete cascade,
  doctor_id bigint references public.doctors (id) on delete set null,
  starts_at timestamptz not null,
  is_available boolean not null default true,
  status text not null default 'disponivel' check (status in ('disponivel', 'reservado', 'indisponivel')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (unit_id, specialty_id, starts_at)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references public.profiles (id) on delete cascade,
  schedule_id bigint not null references public.schedules (id) on delete cascade,
  status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'cancelado')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists appointments_active_schedule_unique
on public.appointments (schedule_id)
where status in ('pendente', 'confirmado');

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_appointments_updated_at on public.appointments;
create trigger set_appointments_updated_at
before update on public.appointments
for each row
execute function public.set_updated_at();

drop trigger if exists set_doctors_updated_at on public.doctors;
create trigger set_doctors_updated_at
before update on public.doctors
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, cpf, phone, unit_id)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'paciente'),
    coalesce(new.raw_user_meta_data ->> 'cpf', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    nullif(new.raw_user_meta_data ->> 'unit_id', '')::bigint
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    cpf = coalesce(nullif(excluded.cpf, ''), public.profiles.cpf),
    phone = coalesce(nullif(excluded.phone, ''), public.profiles.phone),
    unit_id = coalesce(excluded.unit_id, public.profiles.unit_id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.sync_schedule_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_exists boolean;
  target_schedule_id bigint;
begin
  target_schedule_id := coalesce(new.schedule_id, old.schedule_id);

  select exists (
    select 1
    from public.appointments
    where schedule_id = target_schedule_id
      and status in ('pendente', 'confirmado')
  )
  into active_exists;

  update public.schedules
  set
    is_available = not active_exists,
    status = case when active_exists then 'reservado' else 'disponivel' end
  where id = target_schedule_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists sync_schedule_status_after_insert on public.appointments;
create trigger sync_schedule_status_after_insert
after insert on public.appointments
for each row
execute function public.sync_schedule_status();

drop trigger if exists sync_schedule_status_after_update on public.appointments;
create trigger sync_schedule_status_after_update
after update on public.appointments
for each row
execute function public.sync_schedule_status();

drop trigger if exists sync_schedule_status_after_delete on public.appointments;
create trigger sync_schedule_status_after_delete
after delete on public.appointments
for each row
execute function public.sync_schedule_status();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.is_manager()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'gestor'
  );
$$;

create or replace function public.managed_unit_id()
returns bigint
language sql
security definer
set search_path = public
as $$
  select unit_id
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin_or_manager_of(target_unit_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.is_admin()
    or (
      public.is_manager()
      and public.managed_unit_id() = target_unit_id
    )
$$;

create or replace function public.can_manage_schedule(target_schedule_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.is_admin()
    or exists (
      select 1
      from public.schedules s
      join public.profiles p on p.id = auth.uid()
      where s.id = target_schedule_id
        and p.role = 'gestor'
        and p.unit_id = s.unit_id
    )
$$;

alter table public.profiles enable row level security;
alter table public.units enable row level security;
alter table public.doctors enable row level security;
alter table public.specialties enable row level security;
alter table public.schedules enable row level security;
alter table public.appointments enable row level security;

insert into storage.buckets (id, name, public)
values ('unit-images', 'unit-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists unit_images_public_read on storage.objects;
create policy unit_images_public_read
on storage.objects
for select
to public
using (bucket_id = 'unit-images');

drop policy if exists unit_images_admin_insert on storage.objects;
create policy unit_images_admin_insert
on storage.objects
for insert
to authenticated
with check (bucket_id = 'unit-images' and public.is_admin());

drop policy if exists unit_images_admin_update on storage.objects;
create policy unit_images_admin_update
on storage.objects
for update
to authenticated
using (bucket_id = 'unit-images' and public.is_admin())
with check (bucket_id = 'unit-images' and public.is_admin());

drop policy if exists unit_images_admin_delete on storage.objects;
create policy unit_images_admin_delete
on storage.objects
for delete
to authenticated
using (bucket_id = 'unit-images' and public.is_admin());

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin
on public.profiles
for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists profiles_insert_self_or_admin on public.profiles;
create policy profiles_insert_self_or_admin
on public.profiles
for insert
to authenticated
with check (auth.uid() = id or public.is_admin());

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists units_read_authenticated on public.units;
create policy units_read_authenticated
on public.units
for select
to authenticated
using (true);

drop policy if exists units_admin_write on public.units;
create policy units_admin_write
on public.units
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists units_manager_update on public.units;
create policy units_manager_update
on public.units
for update
to authenticated
using (public.is_admin_or_manager_of(id))
with check (public.is_admin_or_manager_of(id));

drop policy if exists specialties_read_authenticated on public.specialties;
create policy specialties_read_authenticated
on public.specialties
for select
to authenticated
using (true);

drop policy if exists specialties_admin_write on public.specialties;
create policy specialties_admin_write
on public.specialties
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists doctors_read_authenticated on public.doctors;
create policy doctors_read_authenticated
on public.doctors
for select
to authenticated
using (true);

drop policy if exists doctors_admin_write on public.doctors;
create policy doctors_admin_write
on public.doctors
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists doctors_manager_write on public.doctors;
create policy doctors_manager_write
on public.doctors
for insert
to authenticated
with check (public.is_admin() or public.is_admin_or_manager_of(unit_id));

drop policy if exists doctors_manager_update on public.doctors;
create policy doctors_manager_update
on public.doctors
for update
to authenticated
using (public.is_admin() or public.is_admin_or_manager_of(unit_id))
with check (public.is_admin() or public.is_admin_or_manager_of(unit_id));

drop policy if exists schedules_read_authenticated on public.schedules;
create policy schedules_read_authenticated
on public.schedules
for select
to authenticated
using (true);

drop policy if exists schedules_admin_write on public.schedules;
create policy schedules_admin_write
on public.schedules
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists schedules_manager_write on public.schedules;
create policy schedules_manager_write
on public.schedules
for insert
to authenticated
with check (public.is_admin() or public.is_admin_or_manager_of(unit_id));

drop policy if exists schedules_manager_update on public.schedules;
create policy schedules_manager_update
on public.schedules
for update
to authenticated
using (public.is_admin() or public.can_manage_schedule(id))
with check (public.is_admin() or public.can_manage_schedule(id));

drop policy if exists appointments_read_owner_or_admin on public.appointments;
create policy appointments_read_owner_or_admin
on public.appointments
for select
to authenticated
using (auth.uid() = patient_id or public.is_admin() or public.can_manage_schedule(schedule_id));

drop policy if exists appointments_insert_owner_or_admin on public.appointments;
create policy appointments_insert_owner_or_admin
on public.appointments
for insert
to authenticated
with check (auth.uid() = patient_id or public.is_admin() or public.can_manage_schedule(schedule_id));

drop policy if exists appointments_update_owner_or_admin on public.appointments;
create policy appointments_update_owner_or_admin
on public.appointments
for update
to authenticated
using (
  auth.uid() = patient_id
  or public.is_admin()
  or public.can_manage_schedule(schedule_id)
)
with check (
  auth.uid() = patient_id
  or public.is_admin()
  or public.can_manage_schedule(schedule_id)
);
